- name: Install Packages
  hosts: all
  tasks:
    - name: Install httpd service
      package:
        name: httpd
        state: installed
        
    - name: Enable httpd service
      service:
        name: httpd
        state: started
        
    - name: Start httpd service
      service:
        name: httpd
        state: started
        
    - name: Install httpd-devel service
      package:
        name: httpd-devel
        state: installed
        
    - name: Install tomcat service
      package:
        name: tomcat
        state: installed
      
  
    
