- name: Install Packages
  hosts: all
  tasks:
    - name: Install httpd service
      package:
        name: httpd
        state: installed
        
    - name: Enable httpd service
      service:
        name: httpd
        state: started
        
    - name: Start httpd service
      service:
        name: httpd
        state: started
      
  
    
