- name: Install Packages
  hosts: all
  gather_facts: no
  tasks:
    - name: Install httpd service
      package:
        name: httpd
        state: installed
    
    - name: Install zip package
      package:
        name: zip
        state: installed
