- name: Install Packages
  hosts: all
  gather_facts: no
  tasks:
    - name: Install httpd service
      service:
        name: httpd
        state: installed
    
    - name: start httpd
      service:
        name="{{ httpd_service }}"
        state: started
      become: yes
  
    - name: restart httpd
      service:
        name="{{ httpd_service }}"
        state: restarted
      become: yes
