- name: Install Packages
  hosts: all
  gather_facts: no
  tasks:
    - name: Install httpd service
      service:
        name: httpd
        state: installed
    
    - name: Start httpd
      service:
        name: httpd
        state: started
      
  
    
